[package]
name = "octale/tokeru"
description = "Fading effect for technically everything"
version = "0.0.5"
authors = ["octale <work@benku.me>", "7kayoh <nanako.matsumooo@outlook.jp>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"