[package]
name = "octale/tokeru"
description = "Fading effect for technically everything"
version = "0.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
